# Generated by Django 4.2.20 on 2025-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models_of_shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=20)),
                ('model_s', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('short', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('size_f', models.CharField(max_length=10)),
                ('size_r', models.FloatField()),
                ('season', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField(max_length=20)),
            ],
        ),
    ]
