# Generated by Django 4.2.20 on 2025-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_of_shoes',
            name='sex',
            field=models.CharField(choices=[('муж.', 'Мужской'), ('жен.', 'Женский')], default='жен.', max_length=10),
        ),
    ]
