# Generated by Django 4.2.20 on 2025-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0002_alter_models_of_shoes_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models_of_shoes',
            options={'verbose_name': 'Модель кроссовок', 'verbose_name_plural': 'Модели кроссовок'},
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='articul',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='model_s',
            field=models.CharField(max_length=20, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='season',
            field=models.CharField(max_length=20, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='sex',
            field=models.CharField(choices=[('муж.', 'Мужской'), ('жен.', 'Женский')], default='жен.', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='short',
            field=models.CharField(max_length=20, verbose_name='Короткий код'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='size_f',
            field=models.CharField(max_length=10, verbose_name='Размер FR'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='size_r',
            field=models.FloatField(verbose_name='Размер RU'),
        ),
    ]
