# Generated by Django 4.2.20 on 2025-04-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0003_alter_models_of_shoes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='models_of_shoes',
            name='sclad',
            field=models.CharField(choices=[('1', 'Ближний'), ('2', 'Дальний')], default='1', max_length=50, verbose_name='Cклад'),
        ),
    ]
