# Generated by Django 4.2.20 on 2025-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0004_models_of_shoes_sclad'),
    ]

    operations = [
        migrations.AddField(
            model_name='models_of_shoes',
            name='picture',
            field=models.ImageField(blank=True, upload_to='models_of_shoes', verbose_name='картинка'),
        ),
    ]
