# Generated by Django 4.2.20 on 2025-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0005_models_of_shoes_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arhiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=20, verbose_name='Артикул')),
                ('model_s', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('short', models.CharField(max_length=20, verbose_name='Короткий код')),
                ('sex', models.CharField(choices=[('муж.', 'Мужской'), ('жен.', 'Женский')], default='жен.', max_length=10, verbose_name='Пол')),
                ('size_f', models.CharField(max_length=10, verbose_name='Размер FR')),
                ('size_r', models.FloatField(verbose_name='Размер RU')),
                ('season', models.CharField(max_length=20, verbose_name='Сезон')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('sclad', models.CharField(choices=[('1', 'Ближний'), ('2', 'Дальний')], default='1', max_length=50, verbose_name='Cклад')),
                ('picture', models.ImageField(blank=True, upload_to='models_of_shoes', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Модель кроссовок',
                'verbose_name_plural': 'Модели кроссовок',
            },
        ),
    ]
