# Generated by Django 4.2.20 on 2025-06-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0006_arhiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
                ('opisanie', models.TextField(verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Sclad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AlterModelOptions(
            name='arhiv',
            options={'verbose_name': 'Архив кроссовок', 'verbose_name_plural': 'Архив кроссовок'},
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='size_f',
            field=models.CharField(max_length=10, verbose_name='Размер USA'),
        ),
        migrations.AlterField(
            model_name='arhiv',
            name='sclad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_of_shoes.sclad', verbose_name='Cклад'),
        ),
        migrations.AlterField(
            model_name='arhiv',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_of_shoes.category', verbose_name='Категория'),
        ),
    ]
