# Generated by Django 4.2.20 on 2025-06-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0007_category_sclad_alter_arhiv_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_of_shoes',
            name='sclad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_of_shoes.sclad', verbose_name='Cклад'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_of_shoes.category', verbose_name='Категория'),
        ),
    ]
