# Generated by Django 4.2.20 on 2025-06-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0008_alter_models_of_shoes_sclad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arhiv',
            options={'ordering': ('id',), 'verbose_name': 'Архив кроссовок', 'verbose_name_plural': 'Архив кроссовок'},
        ),
        migrations.AlterModelOptions(
            name='models_of_shoes',
            options={'ordering': ('id',), 'verbose_name': 'Модель кроссовок', 'verbose_name_plural': 'Модели кроссовок'},
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='sclad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='models_of_shoes.sclad', verbose_name='Cклад'),
        ),
        migrations.AlterField(
            model_name='models_of_shoes',
            name='season',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='models_of_shoes.category', verbose_name='Категория'),
        ),
    ]
