# Generated by Django 4.2.20 on 2025-06-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_of_shoes', '0009_alter_arhiv_options_alter_models_of_shoes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arhiv',
            name='picture_2',
            field=models.ImageField(blank=True, upload_to='models_of_shoes', verbose_name='Картинка (дополнительная)'),
        ),
        migrations.AddField(
            model_name='models_of_shoes',
            name='picture_2',
            field=models.ImageField(blank=True, upload_to='models_of_shoes', verbose_name='Картинка (дополнительная)'),
        ),
    ]
